In [1]:
1-2

-1

In [2]:
4 * 5


20

In [3]:
7 / 5


1.4

In [4]:
3 ** 2

9

In [5]:
type(10)

int

In [6]:
type(2.718)

float

In [7]:
type("hello")

str

In [8]:
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [9]:
len(a)

5

In [10]:
a[0]

1

In [11]:
a[4]

5

In [12]:
a[4] = 99

In [13]:
a

[1, 2, 3, 4, 99]

In [14]:
me= {'height': 180}
me['height']

180

In [15]:
hungry = True
if hungry:
    print("I'm hungry")

I'm hungry


In [16]:
hungry = False
if hungry:
    print("I'm hungry")

In [17]:
for i in [1,2,3]:
    print(i)

1
2
3


In [18]:
def hello():
    print("Hello World!")

hello()

Hello World!


In [19]:
class Man:
    def __init__(self, name):
        self.name = name
        print("Initialized!")

    def hello(self):
        print("Hello World")

    def goodbye(self):
        print("Good-bye " + self.name + "!")

m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello World
Good-bye David!


In [20]:
import numpy as np

In [21]:
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [22]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [23]:
x-y

array([-1., -2., -3.])

In [24]:
x / y

array([0.5, 0.5, 0.5])

In [25]:
x/2.0

array([0.5, 1. , 1.5])

In [26]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [27]:
A.shape

(2, 2)

In [28]:
A.dtype

dtype('int32')

In [29]:
B = np.array([[3, 0 ], [0,6]])
A * B

array([[ 3,  0],
       [ 0, 24]])